# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='fips',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
