# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_county_fips'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='type',
            field=models.CharField(choices=[['STL', 'state upper'], ['STU', 'state lower'], ['FED', 'congressional']], default='', max_length=100),
            preserve_default=False,
        ),
    ]
