# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_district_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbr',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='state',
            name='geometry'
        ),
        migrations.AddField(
            model_name='state',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
