# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170209_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='geometry',
        ),
        migrations.AddField(
            model_name='state',
            name='mp_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='state',
            name='p_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
