# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contest_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Candidate'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='type',
            field=models.CharField(choices=[['MU', 'municipal'], ['ST', 'state'], ['FED', 'federal'], ['PRES', 'presidential'], ['SEN', 'senate']], max_length=100),
        ),
    ]
