# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170209_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contest'),
        ),
    ]
